version: "3.8"
services:
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=eringiv3
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5439:5432"
volumes:
  postgres:
